key_to_char = {
    96: "`",
    126: "~",
    49: "1",
    33: "!",
    50: "2",
    64: "@",
    51: "3",
    35: "#",
    52: "4",
    36: "$",
    53: "5",
    37: "%",
    54: "6",
    94: "^",
    55: "7",
    38: "&",
    56: "8",
    42: "*",
    57: "9",
    40: "(",
    48: "0",
    41: ")",
    45: "-",
    95: "_",
    61: "=",
    43: "+",
    16777219: "delete",
    16777217: "tab",
    16777218: "shift tab",
    81: "q",
    87: "w",
    69: "e",
    82: "r",
    84: "t",
    89: "y",
    85: "u",
    73: "i",
    79: "o",
    80: "p",
    91: "[",
    123: "{",
    93: "]",
    125: "}",
    92: "\\",
    124: "|",
    16777252: "caps lock",
    65: "a",
    83: "s",
    68: "d",
    70: "f",
    71: "g",
    72: "h",
    74: "j",
    75: "k",
    76: "l",
    59: ";",
    58: ":",
    39: "'",
    34: '"',
    16777220: "return",
    90: "z",
    88: "x",
    67: "c",
    86: "v",
    66: "b",
    78: "n",
    77: "m",
    44: ",",
    60: "<",
    46: ".",
    62: ">",
    47: "/",
    63: "?",
    16777248: "shift",
    32: "space",
    16777216: "esc",
}

keyboard = {
    1: {
        1: {"text": ["~", "`"], "code": {96, 126}, "type": "square", "side": "c"},
        2: {"text": ["!", "1"], "code": {33, 49}, "type": "square", "side": "c"},
        3: {"text": ["@", "2"], "code": {64, 50}, "type": "square", "side": "c"},
        4: {"text": ["#", "3"], "code": {35, 51}, "type": "square", "side": "c"},
        5: {"text": ["$", "4"], "code": {36, 52}, "type": "square", "side": "c"},
        6: {"text": ["%", "5"], "code": {37, 53}, "type": "square", "side": "c"},
        7: {"text": ["^", "6"], "code": {94, 54}, "type": "square", "side": "c"},
        8: {"text": ["&", "7"], "code": {38, 55}, "type": "square", "side": "c"},
        9: {"text": ["*", "8"], "code": {42, 56}, "type": "square", "side": "c"},
        10: {"text": ["(", "9"], "code": {40, 57}, "type": "square", "side": "c"},
        11: {"text": [")", "0"], "code": {41, 48}, "type": "square", "side": "c"},
        12: {"text": ["_", "-"], "code": {95, 45}, "type": "square", "side": "c"},
        13: {"text": ["+", "="], "code": {43, 61}, "type": "square", "side": "c"},
        14: {"text": ["delete"], "code": {16777219}, "type": "rec-s", "side": "r"},
    },
    2: {
        1: {
            "text": ["tab"],
            "code": {16777217, 16777218},
            "type": "rec-s",
            "side": "l",
        },
        2: {"text": ["Q"], "code": {81}, "type": "square", "side": "c"},
        3: {"text": ["W"], "code": {87}, "type": "square", "side": "c"},
        4: {"text": ["E"], "code": {69}, "type": "square", "side": "c"},
        5: {"text": ["R"], "code": {82}, "type": "square", "side": "c"},
        6: {"text": ["T"], "code": {84}, "type": "square", "side": "c"},
        7: {"text": ["Y"], "code": {89}, "type": "square", "side": "c"},
        8: {"text": ["U"], "code": {85}, "type": "square", "side": "c"},
        9: {"text": ["I"], "code": {73}, "type": "square", "side": "c"},
        10: {"text": ["O"], "code": {79}, "type": "square", "side": "c"},
        11: {"text": ["P"], "code": {80}, "type": "square", "side": "c"},
        12: {"text": ["{", "["], "code": {91, 123}, "type": "square", "side": "c"},
        13: {"text": ["}", "]"], "code": {93, 125}, "type": "square", "side": "c"},
        14: {"text": ["|", "\\"], "code": {92, 124}, "type": "square", "side": "c"},
    },
    3: {
        1: {"text": ["caps lock"], "code": {16777252}, "type": "rec-m", "side": "l"},
        2: {"text": ["A"], "code": {65}, "type": "square", "side": "c"},
        3: {"text": ["S"], "code": {83}, "type": "square", "side": "c"},
        4: {"text": ["D"], "code": {68}, "type": "square", "side": "c"},
        5: {"text": ["F"], "code": {70}, "type": "square", "side": "c"},
        6: {"text": ["G"], "code": {71}, "type": "square", "side": "c"},
        7: {"text": ["H"], "code": {72}, "type": "square", "side": "c"},
        8: {"text": ["J"], "code": {74}, "type": "square", "side": "c"},
        9: {"text": ["K"], "code": {75}, "type": "square", "side": "c"},
        10: {"text": ["L"], "code": {76}, "type": "square", "side": "c"},
        11: {"text": [":", ";"], "code": {59, 58}, "type": "square", "side": "c"},
        12: {"text": ['"', "'"], "code": {34, 39}, "type": "square", "side": "c"},
        13: {"text": ["return"], "code": {16777220}, "type": "rec-m", "side": "r"},
    },
    4: {
        1: {"text": ["shift"], "code": {16777248}, "type": "rec-l", "side": "l"},
        2: {"text": ["Z"], "code": {90}, "type": "square", "side": "c"},
        3: {"text": ["X"], "code": {88}, "type": "square", "side": "c"},
        4: {"text": ["C"], "code": {67}, "type": "square", "side": "c"},
        5: {"text": ["V"], "code": {86}, "type": "square", "side": "c"},
        6: {"text": ["B"], "code": {66}, "type": "square", "side": "c"},
        7: {"text": ["N"], "code": {78}, "type": "square", "side": "c"},
        8: {"text": ["M"], "code": {77}, "type": "square", "side": "c"},
        9: {"text": ["<", ","], "code": {60, 44}, "type": "square", "side": "c"},
        10: {"text": [">", "."], "code": {62, 46}, "type": "square", "side": "c"},
        11: {"text": ["?", "/"], "code": {63, 47}, "type": "square", "side": "c"},
        12: {"text": ["shift"], "code": {16777248}, "type": "rec-l", "side": "r"},
    },
    5: {
        1: {"text": [""], "code": {-1}, "type": "empty-l-space", "side": "c"},
        2: {"text": [""], "code": {32}, "type": "space", "side": "c"},
        3: {"text": [""], "code": {-1}, "type": "empty-r-space", "side": "c"},
    },
}
